index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home/index.html.twig'

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

home:
    path: /home
    controller: App\Controller\DefaultController::home

register:
    path: /register
    controller: App\Controller\UserController::register
    defaults:
        template: 'home/index.html.twig'  

login_get:
    path: /login
    controller: App\Controller\UserController::getLogin
    methods: GET

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: POST

register_post:
    path: /register_post
    controller: App\Controller\DefaultController::register

logout:
    path: /logout
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home/index.html.twig'
    

