index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home/index.html.twig'

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

home:
    path: /home
    controller: App\Controller\DefaultController::home

register:
    path: /register
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: 'home/register.html.twig'  

register_post:
    path: /register
    controller: App\Controller\UserController::register
    methods: POST

login_get:
    path: /login
    controller: App\Controller\UserController::getLogin
    methods: GET

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: POST

logout:
    path: /logout
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true

add-event:
    path: /home/event/add
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home/register-event.html.twig'

add-event-post:
    path: /api/event/add
    controller: App\Controller\EventController::register
    methods: POST
    

